### ISSUE TITLE
Libcloud DNS responder doesn't work with Route 53

### ISSUE THREAD

**Issue by glyph** [twisted/txacme#120]
Due to https://issues.apache.org/jira/browse/LIBCLOUD-875 this does not work with Route 53 DNS.

Possible solutions:

- just fix the upstream issue
- special-case AWS driver to work around it
- talk to route53 via boto instead

Since this is a separate, higher-level issue than #85 I figured it should be filed separately.

**Comment by Lukasa** [comment]
I've got a branch for creating a txaws-based Route53 backend. Is this likely to be of interest to people?

**Comment by Lukasa** [comment]
I should note that it requires the current master branch of txaws, so we'd need a new release of txaws.

**Comment by glyph** [comment]
Absolutely.  Feel free to open the PR here with a dep on a pinned git hash rather than a release so that we can get code review out of the way before the upstream release is done.

Is @exarkun a maintainer on txaws?

**Comment by exarkun** [comment]
Uh I have commit and did the last couple releases.  That's all.

**Comment by glyph** [comment]
Sounds like a "yes" then? :)  Any interest in helping this one along?

**Comment by exarkun** [comment]
Do a release of txAWS?  Probably can be done.

**Comment by glyph** [comment]
This will make https://github.com/glyph/lancer useful to a *lot* more people :)

**Comment by tonybaloney** [comment]
@glyph @Lukasa WIP fixes https://github.com/apache/libcloud/pull/1093

**Comment by tonybaloney** [comment]
Patch merged in Libcloud, will be released in 2.2.0, which will go out next week.

Please, can you validate this works with your scenario? @glyph @Lukasa

**Comment by glyph** [comment]
Put it on the to-do list for this week, although I hope someone else beats me to it :)

**Comment by mithrandi** [comment]
@tonybaloney I have just confirmed that the txacme integration tests pass against Route 53 using Libcloud from git, so everything looks good here.

**Comment by tonybaloney** [comment]
Version of Apache-libcloud with fix is 2.2.0, released on PyPi https://pypi.org/project/apache-libcloud/2.2.0/ 
Fix is now part of stable release.
@mithrandi @glyph @Lukasa

**Comment by glyph** [comment]
A bit late to the party here, but just wanted to say thanks a ton @tonybaloney for following up on this and getting it fixed & released.
