### ISSUE TITLE
txacme.client.Client.register raised KeyError when an ACME v2 directory is used

### ISSUE THREAD

**Issue by adiroiban** [twisted/txacme#147]
I think that first, Client.register should return a deferred with a failure, instead of raising the exception. 
Is not a big deal, but it makes it easy to use the code as you only have to add the errback, and not also use try/except.

Second, instead of just `KeyError('Directory field not found',)` I would prefer something like `"new-reg" field not found in the directory.'
In this way, is easier to know which field was not found

**Comment by glyph** [comment]
@adiroiban presumably we just need to implement ACME v2 now (c.f. #151) rather than fixing the error-reporting here, or txacme will shortly be useless? :)

**Comment by adiroiban** [comment]
Yes. This can be closed.
