### ISSUE TITLE
Eliot > 1.7 doesn't work with Python 3.5.2, which is what is on Ubuntu Xenial

### ISSUE THREAD

**Issue by itamarst** [twisted/txacme#149]
See https://github.com/itamarst/eliot/issues/418

I suggest that txacme pin to Eliot < 1.8 when it is installed on Python 3.5, which I _think_ you can express in setuptools.

**Comment by glyph** [comment]
I think there's a thing that Eliot itself can do that will fix this for all projects, not just txacme?  Where you like… do a new `.post` release with some metadata that says it only works on the new version, then pull the old release from PyPI?

paging @dstufft to the thread

**Comment by glyph** [comment]
(Per previous comments, I am going to say that this isn't txacme's problem.)
