### ISSUE TITLE
broken with attrs 19.2.0

### ISSUE THREAD

**Issue by glyph** [twisted/txacme#150]
```
  File "/code/env/site-packages/txacme/_endpoint_parser.py", line 27, in parseStreamServer
    from txacme.endpoint import _parse
  File "/code/env/site-packages/txacme/endpoint.py", line 24, in <module>
    from txacme.store import DirectoryStore
  File "/code/env/site-packages/txacme/store.py", line 16, in <module>
    class DirectoryStore(object):
  File "/code/env/site-packages/txacme/store.py", line 20, in DirectoryStore
    path = attr.ib(convert=methodcaller('asTextMode'))
exceptions.TypeError: attrib() got an unexpected keyword argument 'convert'
```

**Comment by glyph** [comment]
cc @hynek @mithrandi

**Comment by hynek** [comment]
That’s been throwing a DeprecationWarning since 2017. 😇 Bump dependency to 17.4 and replace `convert` to `converter`. 

While doing so you may want to look for uses of `cmp` which will break mid-2021. 🤪

**Comment by glyph** [comment]
Apparently fixed… some time ago… in https://github.com/twisted/txacme/pull/137

**Comment by hynek** [comment]
Well, One-Year-of-Deprecation-Warnings is useless, when a project is released every two years. 🙃 Same offer I made elsewhere: I’ll fix the cmp warning for you if you tell me your preferred approach.

**Comment by mithrandi** [comment]
Leaving open for `cmp`.

**Comment by glyph** [comment]
Let's have a separate issue for `cmp=`, since the description is no longer accurate.
